project:
  type: book
  output-dir: docs

book:
  title: "Spanish"
  chapters:
    - index.qmd
    - i_l1.qmd
    - i_l2.qmd
    - i_l3.qmd
    - i_l4.qmd
    - i_l5.qmd
    - i_l6.qmd
    - i_l7.qmd
    - i_l8.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: paper
      dark: darkly

  pdf:
    documentclass: scrreprt



