---
editor: 
  markdown: 
    wrap: 72
---

# Verb Directory {.unnumbered}

---

::: {.panel-tabset}

# Verbs

:::: {.columns}

::: {.column width="40%"}

**[COMMON VERBS](i_l1.html)**

-   ser
-   estar
-   tener
-   poder
-   hacer
-   ir/irse

:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="40%"}

**[DISPOSITION VERBS](i_l2.html)**

-   querer
-   deber
-   necesitar
-   gustarse

:::

::::

---

:::: {.columns}

::: {.column width="40%"}

**[COGNITION VERBS](i_l3.html)**

-   pensar
-   esperar
-   creer
-   saber
-   conocer
-   parecer
-   suponer
-   sentir/sentirse


:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="40%"}

**[LEARNING VERBS](i_l4.html)**

-   escribir
-   estudiar
-   leer
-   entender
-   aprender
-   decir
-   hablar
-   llamar/llamarse


:::

::::

---

:::: {.columns}

::: {.column width="40%"}


**[SENSING VERBS](i_l5.html)**


-   mirar
-   ver
-   oír
-   escuchar
-   dar
-   tomar
-   poner/ponerse

:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="40%"}


**[MOVEMENT A VERBS](i_l6.html)**


-   entrar
-   llegar
-   venir
-   seguir
-   caminar
-   andar
-   quedarse
-   salir
-   dejar

:::

::::

---

:::: {.columns}

::: {.column width="40%"}

**[MOVEMENT B VERBS](i_l7.html)**

-   acabar
-   comenzar
-   llevar
-   traer
-   pasar
-   cercar/cercarse
-   caer/caerse
-   volver
-   terminar

:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="40%"}


**[LIFE VERBS](i_l8.html)**

-   vivir
-   comer
-   cantar
-   ayudar
-   trabajar
-   comprar
-   pagar
-   manejar
-   conducir
-   construir
-   haber
-   contar
-   perder

:::


# Other important verbs:

Verbs that are absolutely essential to Spanish conversation but not included here are:

| Spanish Verb   | English Meaning               |
|:---------------|:------------------------------|
| pedir          | to ask for/order              |
| cambiar        | to change                     |
| buscar         | to search/look for            |
| dormir         | to sleep                      |
| jugar          | to play (a game or sport)     |
| intentar       | to try                        |
| empezar        | to begin                      |
| recordar       | to remember                   |
| olvidar        | to forget                     |
| tocar          | to touch/play (an instrument) |
| decidir        | to decide                     |
| mostrar        | to show                       |
| correr         | to run                        |
| probar         | to try/test                   |
| desear         | to wish/desire                |
| recibir        | to receive                    |
| bailar         | to dance                      |
| repetir        | to repeat                     |
| enviar         | to send                       |
| vender         | to sell                       |
| resolver       | to solve                      |
| coger          | to take (in Spain)            |
| romper         | to break                      |
| girar          | to turn                       |
| morir          | to die                        |
| nacer          | to be born                    |


::::

# Game

**Spanish Verb Conjugation Game**

```{=html}
<iframe width="780" height="500" src="https://ajaverett.shinyapps.io/spanish_quiz/" ></iframe>
```
  

:::